### ISSUE TITLE
some interesting comments

### ISSUE THREAD

**Issue by kiwichen2003** [mattroconnor/deep_learning_coronavirus_cure#2]
Here are some interesting comments of your implementation.
1. The SMILES of your Remdesivir from DrugBank: 
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@](C#N)([C@H](O)[C@@H]1O)C1=CC=C2N1N=CN=C2N)OC1=CC=CC=C1

is different from PubChem: 
CCC(CC)COC(=O)C(C)NP(=O)(OCC1C(C(C(O1)(C#N)C2=CC=C3N2N=CN=C3N)O)O)OC4=CC=CC=C4
it will cause different binding affinity. 

2. you may didn't set the molecular active site or set to max. range. it makes binding affinity so high.

3. the generated results looks not drug-like. 

anyway, good job  :)

**Comment by mattroconnor** [comment]
Thanks, yes my initial results themselves may only be theoretical and impractical due to not accounting for full-suite of real-world constraints, however the overall approach seems to demonstrate promising results, and I am refining it by adding additional constraints to optimize for. If you have any suggestions of metrics to evaluate "drug-likeness" such that that too can be optimized for, that would be very helpful
